/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (4.3.1).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.example.entrevueSpringBoot.controller;



import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import com.example.entrevueSpringBoot.dto.ReponseFilm;
import com.example.entrevueSpringBoot.dto.RequeteCreationFilm;


@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2023-02-14T10:53:35.208341800-05:00[America/New_York]")

@Validated
public interface FilmApi {

    /**
     * POST /api/films : Crée un film
     *
     * @param requeteCreationFilm  (required)
     * @return Created (status code 200)
     */

    @RequestMapping(value = "/api/films",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<ReponseFilm> creeFilm( @RequestBody RequeteCreationFilm requeteCreationFilm);


    /**
     * GET /api/films/{id} : Obtenir tous les film disponible
     *
     * @param id  (required)
     * @return OK (status code 200)
     */

    @RequestMapping(value = "/api/films/{id}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<ReponseFilm> obtenirFilm( @PathVariable("id") Integer id);

}
